env:
  browser: true
  commonjs: true
  es6: true
extends: "eslint:recommended"
parserOptions:
  ecmaFeatures:
    jsx: false
  ecmaVersion: 2020
  sourceType: module
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - 0
  no-console:
    - 0
globals:
  __dirname: true
  after: true
  afterEach: true
  before: true
  beforeEach: true
  Buffer: true
  define: true
  describe: true
  expect: true
  it: true
  process: true